use std::{fmt::Display, str::FromStr};

// The curated 4-letter CVCV pools (4096 each — see design/names.md).
// Generated by scripts/curate/export.py into pools.rs; do not edit here.
use crate::pools::{PREFIXES, SUFFIXES};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Name(u64);

impl Name {
    /// Maximum number of names that will ever exist (2^40 ≈ 1 trillion).
    /// Registration is capped here — in the code, not just the contract.
    pub const MAX_ORDINALS: u64 = 1 << 40;

    /// Creates a unique Name from the ordinal of on-chain registration.
    ///
    /// Ordinals are capped at [`MAX_ORDINALS`](Self::MAX_ORDINALS): a name
    /// cannot be produced for an ordinal at or beyond the cap — this returns
    /// an error rather than silently mapping onto another ordinal's name.
    pub fn from_ordinal(ordinal: u64) -> Result<Self, &'static str> {
        if ordinal >= Self::MAX_ORDINALS {
            return Err("ordinal at or beyond the 2^40 name cap");
        }
        Ok(Self(permute_ordinal(ordinal)))
    }

    /// Recovers the ordinal used to create this Name (inverse of `from_ordinal`).
    pub fn to_ordinal(&self) -> u64 {
        unpermute_ordinal(self.0)
    }

    /// The internal 48-bit permuted value used for wire encoding and name display.
    pub fn as_u64(&self) -> u64 {
        self.0
    }

    /// Reconstruct a [`Name`] from its internal 48-bit value (the same value
    /// returned by [`Name::as_u64`]).
    pub fn from_raw(val: u64) -> Self {
        Name(val & MASK_48)
    }

    /// Encode the internal 48-bit value as 6 bytes (big-endian) for wire format.
    pub fn to_wire_bytes(&self) -> [u8; 6] {
        let be = self.0.to_be_bytes();
        [be[2], be[3], be[4], be[5], be[6], be[7]]
    }

    /// Decode a [`Name`] from 6 wire-format bytes (big-endian, 48 bits).
    pub fn from_wire_bytes(wire: &[u8; 6]) -> Self {
        let mut buf = [0u8; 8];
        buf[2..8].copy_from_slice(wire);
        Name(u64::from_be_bytes(buf))
    }

    /// Returns the canonical zone domain for this Name.
    pub fn canonical_domain(&self) -> String {
        format!("{}.mns.alt", self.encode())
    }

    pub(crate) fn encode(&self) -> String {
        let val = self.0;
        let mut result = String::with_capacity(17); // 8 + '-' + 8
        encode_word((val >> 24) & MASK_24, &mut result);
        result.push('-');
        encode_word(val & MASK_24, &mut result);
        result
    }

}

impl Display for Name {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.encode())
    }
}

impl FromStr for Name {
    type Err = &'static str;

    /// Parse a [`Name`] from a string.
    ///
    /// Accepts a bare name (`davufezo-hosojise`), a DNS label
    /// (`davufezo-hosojise.mns.alt`), or any string containing the
    /// `XXXXXXXX-XXXXXXXX` pattern. When multiple patterns are present the
    /// **rightmost** match (the domain apex) is returned.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if !s.is_ascii() {
            return Err("name must be ASCII");
        }

        if s.len() == 17 && s.as_bytes()[8] == b'-' {
            return Ok(Name(decode(s)?));
        }

        let bytes = s.as_bytes();
        for start in (0..bytes.len().saturating_sub(16)).rev() {
            if bytes[start + 8] == b'-' {
                let candidate =
                    std::str::from_utf8(&bytes[start..start + 17]).map_err(|_| "invalid UTF-8")?;
                if let Ok(val) = decode(candidate) {
                    return Ok(Name(val));
                }
            }
        }
        Err("could not find a valid mns name in the string")
    }
}

const MASK_24: u64 = 0xFF_FFFF;
const MASK_48: u64 = 0xFFFF_FFFF_FFFF;

#[inline(always)]
fn round_f(val: u64, r: u64) -> u64 {
    (val.wrapping_mul(r) ^ (val >> 7) ^ (val << 13)) & MASK_24
}

/// A 48-bit bijective permutation. No collisions across [0, 2^48).
/// Feistel network with 4 rounds (same shape as scripts/curate/sample.py).
pub(crate) fn permute_ordinal(x: u64) -> u64 {
    // Offset by one to avoid permuting 0 to 0.
    let x = x.wrapping_add(1) & MASK_48;
    let mut left = (x >> 24) & MASK_24;
    let mut right = x & MASK_24;
    const R: [u64; 4] = [0x9E3770, 0x6C62D0, 0xB5A4B0, 0xD2F3E0];
    for &r in &R {
        let next_right = left ^ round_f(right, r);
        left = right;
        right = next_right;
    }
    (left << 24) | right
}

/// Inverse of `permute_ordinal`.
pub(crate) fn unpermute_ordinal(x: u64) -> u64 {
    let mut left = (x >> 24) & MASK_24;
    let mut right = x & MASK_24;
    const R: [u64; 4] = [0x9E3770, 0x6C62D0, 0xB5A4B0, 0xD2F3E0];
    for &r in R.iter().rev() {
        let prev_left = right ^ round_f(left, r);
        right = left;
        left = prev_left;
    }
    ((left << 24) | right).wrapping_sub(1) & MASK_48
}

/// Encode a 24-bit value into 8 characters: PREFIX(12 bits) + SUFFIX(12 bits).
fn encode_word(bits: u64, out: &mut String) {
    let hi = ((bits >> 12) & 0xFFF) as usize; // prefix index
    let lo = (bits & 0xFFF) as usize; // suffix index

    out.push_str(PREFIXES[hi]);
    out.push_str(SUFFIXES[lo]);
}

fn decode(encoded: &str) -> Result<u64, &'static str> {
    if !encoded.is_ascii() {
        return Err("name must be ASCII");
    }
    let bytes = encoded.as_bytes();
    if bytes.len() != 17 || bytes[8] != b'-' {
        return Err("name must be 17 characters in the form XXXXXXXX-XXXXXXXX");
    }
    let hi = decode_word(&bytes[0..8])?;
    let lo = decode_word(&bytes[9..17])?;
    Ok((hi << 24) | lo)
}

/// Decode an 8-byte slice (PREFIX 4 chars + SUFFIX 4 chars) into 24 bits.
fn decode_word(word: &[u8]) -> Result<u64, &'static str> {
    debug_assert_eq!(word.len(), 8);

    let prefix_str = std::str::from_utf8(&word[0..4]).map_err(|_| "invalid UTF-8 in prefix")?;
    let suffix_str = std::str::from_utf8(&word[4..8]).map_err(|_| "invalid UTF-8 in suffix")?;

    let prefix_idx = PREFIX_LUT.lookup(prefix_str).ok_or("unknown prefix")? as u64;
    let suffix_idx = SUFFIX_LUT.lookup(suffix_str).ok_or("unknown suffix")? as u64;

    Ok((prefix_idx << 12) | suffix_idx)
}

/// Slots: (packed_key, index). packed_key == u32::MAX means empty.
struct Lut<const N: usize> {
    slots: [(u32, u16); N],
}

impl<const N: usize> Lut<N> {
    const fn build(list: &[&str; 4096]) -> Self {
        let mut slots = [(u32::MAX, 0u16); N];
        let mut i = 0usize;
        while i < 4096 {
            let b = list[i].as_bytes();
            let key = (b[0] as u32)
                | ((b[1] as u32) << 8)
                | ((b[2] as u32) << 16)
                | ((b[3] as u32) << 24);
            let mut slot = ((key ^ (key >> 16)) as usize) & (N - 1);
            loop {
                if slots[slot].0 == u32::MAX {
                    slots[slot] = (key, i as u16);
                    break;
                }
                slot = (slot + 1) & (N - 1);
            }
            i += 1;
        }
        Self { slots }
    }

    fn lookup(&self, s: &str) -> Option<u16> {
        if s.len() != 4 {
            return None;
        }
        let b = s.as_bytes();
        let key = (b[0] as u32)
            | ((b[1] as u32) << 8)
            | ((b[2] as u32) << 16)
            | ((b[3] as u32) << 24);
        let mut slot = ((key ^ (key >> 16)) as usize) & (N - 1);
        loop {
            let (k, v) = self.slots[slot];
            if k == u32::MAX {
                return None;
            }
            if k == key {
                return Some(v);
            }
            slot = (slot + 1) & (N - 1);
        }
    }
}

// N = 8192: power of two, > 4096, keeps load factor < 0.5.
static PREFIX_LUT: Lut<8192> = Lut::build(&PREFIXES);
static SUFFIX_LUT: Lut<8192> = Lut::build(&SUFFIXES);

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::*;

    #[test]
    fn test_lut_uniqueness_and_integrity() {
        // 1. Verify Prefix List Uniqueness
        let mut prefix_set = HashSet::new();
        for &p in &PREFIXES {
            assert!(prefix_set.insert(p), "DUPLICATE PREFIX DETECTED: {}", p);
            assert_eq!(p.len(), 4, "Prefix {} is not 4 chars", p);
        }

        // 2. Verify Suffix List Uniqueness
        let mut suffix_set = HashSet::new();
        for &s in &SUFFIXES {
            assert!(suffix_set.insert(s), "DUPLICATE SUFFIX DETECTED: {}", s);
            assert_eq!(s.len(), 4, "Suffix {} is not 4 chars", s);
        }
    }

    #[test]
    fn test_lut_round_trip_all_prefixes() {
        for (i, &p) in PREFIXES.iter().enumerate() {
            assert_eq!(
                PREFIX_LUT.lookup(p),
                Some(i as u16),
                "prefix '{p}' at index {i}"
            );
        }
    }

    #[test]
    fn test_lut_round_trip_all_suffixes() {
        for (i, &s) in SUFFIXES.iter().enumerate() {
            assert_eq!(
                SUFFIX_LUT.lookup(s),
                Some(i as u16),
                "suffix '{s}' at index {i}"
            );
        }
    }

    #[test]
    fn test_no_forbidden_letters_in_lists() {
        for &p in &PREFIXES {
            for bad in ['c', 'q', 'x', 'y'] {
                assert!(!p.contains(bad), "prefix '{p}' contains forbidden {bad}");
            }
        }
        for &s in &SUFFIXES {
            for bad in ['c', 'q', 'x', 'y'] {
                assert!(!s.contains(bad), "suffix '{s}' contains forbidden {bad}");
            }
        }
    }

    #[test]
    fn test_name_length_and_format() {
        for ordinal in [0u64, 1, 42, 1_000_000, 1_099_511_627_775] {
            let name = Name::from_ordinal(ordinal).unwrap().to_string();
            assert_eq!(name.len(), 17, "name '{name}' should be 17 chars");
            assert_eq!(&name[8..9], "-", "dash should be at position 8 in '{name}'");
        }
    }

    #[test]
    fn test_ordinal_roundtrip() {
        for ordinal in [0u64, 1, 2, 42, 255, 1_000, 1_000_000, 1_099_511_627_775] {
            let name = Name::from_ordinal(ordinal).unwrap();
            assert_eq!(
                name.to_ordinal(),
                ordinal,
                "ordinal roundtrip failed for {ordinal}"
            );
        }
    }

    #[test]
    fn test_string_roundtrip() {
        for ordinal in [0u64, 1, 42, 1_000_000, 1_099_511_627_775] {
            let name = Name::from_ordinal(ordinal).unwrap();
            let encoded = name.to_string();
            let decoded: Name = encoded.parse().expect("parse failed");
            assert_eq!(
                name, decoded,
                "string roundtrip failed for ordinal {ordinal}: '{encoded}'"
            );
        }
    }

    #[test]
    fn test_name_regression_golden_values() {
        // Update these by running the test once with `-- --nocapture` and
        // recording the output, then paste the values here.
        let cases: &[(u64, &str)] = &[
            (0, "davufezo-hosojise"),
            (1, "danuhuni-mojavake"),
            (42, "lehuwadi-zakatari"),
            (1_000_000, "gamogozi-zagutowe"),
            (1_099_511_627_775, "bodebada-senotuse"),
        ];
        for &(ordinal, expected) in cases {
            let actual = Name::from_ordinal(ordinal).unwrap().to_string();
            assert_eq!(
                actual, expected,
                "regression failure for ordinal {ordinal}: got '{actual}', expected '{expected}'"
            );
        }
    }

    #[test]
    #[ignore]
    fn check_names_for_ordinals() {
        for ordinal in 0..=6_u64 {
            let name = Name::from_ordinal(ordinal).unwrap();
            println!("{ordinal:>4}: {name}");
            // println!("{}", name.render_avatar_svg());
        }
    }

    #[test]
    #[ignore]
    fn test_global_uniqueness_and_diffusion() {
        use rayon::prelude::*;

        let count: u64 = 10_000_000;
        let chunk_size: u64 = 100_000;
        let num_chunks = count.div_ceil(chunk_size);

        let chunk_heads: Vec<u64> = (0..num_chunks)
            .map(|c| Name::from_ordinal(c * chunk_size).unwrap().as_u64())
            .collect();

        let results: Vec<(Vec<u64>, u64)> = (0..num_chunks)
            .into_par_iter()
            .map(|chunk| {
                let start = chunk * chunk_size;
                let end = (start + chunk_size).min(count);
                let mut values = Vec::with_capacity((end - start) as usize);
                let mut bit_diff: u64 = 0;
                let mut prev = Name::from_ordinal(start).unwrap().as_u64();
                values.push(prev);
                for ordinal in (start + 1)..end {
                    let v = Name::from_ordinal(ordinal).unwrap().as_u64();
                    bit_diff += (v ^ prev).count_ones() as u64;
                    prev = v;
                    values.push(v);
                }
                (values, bit_diff)
            })
            .collect();

        let mut total_bit_diff: u64 = results.iter().map(|(_, d)| d).sum();
        let all_values: Vec<Vec<u64>> = results.into_iter().map(|(v, _)| v).collect();

        for i in 1..chunk_heads.len() {
            let last_of_prev = *all_values[i - 1].last().unwrap();
            total_bit_diff += (chunk_heads[i] ^ last_of_prev).count_ones() as u64;
        }

        let mut flat: Vec<u64> = all_values.into_iter().flatten().collect();
        flat.par_sort_unstable();
        let original_len = flat.len();
        flat.dedup();
        assert_eq!(
            flat.len(),
            original_len,
            "COLLISION DETECTED in first {count} ordinals"
        );

        println!("Tested {} IDs with 0 collisions.", flat.len());

        let avg_bit_diff = total_bit_diff as f32 / (count - 1) as f32;
        println!("Average bits changed between adjacent IDs: {avg_bit_diff:.2} / 48");
        assert!(
            (avg_bit_diff - 24.0).abs() < 0.10,
            "Poor diffusion: avg bit diff = {avg_bit_diff}"
        );
    }

    #[test]
    fn test_ordinal_cap() {
        // the maximum valid ordinal works and round-trips
        let name = Name::from_ordinal(Name::MAX_ORDINALS - 1).unwrap();
        assert_eq!(name.to_ordinal(), Name::MAX_ORDINALS - 1);
        assert_eq!(name.to_string(), "bodebada-senotuse");
    }

    #[test]
    fn test_ordinal_over_cap_errors() {
        assert!(Name::from_ordinal(Name::MAX_ORDINALS).is_err());
        assert!(Name::from_ordinal(u64::MAX).is_err());
    }

    #[test]
    fn test_from_str_first_label() {
        // A full DNS name — should pick the rightmost (apex) label.
        let s = "sub-label.foo.davufezo-hosojise.mns.alt";
        let name: Name = s.parse().expect("parse DNS name");
        assert_eq!(name.to_string(), "davufezo-hosojise");
    }

    #[test]
    fn test_from_str_only_name() {
        let name: Name = "davufezo-hosojise".parse().unwrap();
        assert_eq!(name.to_string(), "davufezo-hosojise");
    }

    #[test]
    fn test_from_str_url_name() {
        let name: Name = "https://davufezo-hosojise.mns.mlkut.org".parse().unwrap();
        assert_eq!(name.to_string(), "davufezo-hosojise");
    }

    #[test]
    fn test_from_str_no_suffix_fails() {
        assert!("example.com".parse::<Name>().is_err());
        assert!("foo.bar.baz".parse::<Name>().is_err());
    }

    #[test]
    fn test_from_str_trailing_dot() {
        // FQDN with trailing dot
        let s = "lehuwadi-zakatari.";
        let name: Name = s.parse().expect("parse FQDN");
        assert_eq!(name.to_string(), "lehuwadi-zakatari");
    }

    #[test]
    fn test_from_str_dash_prefix() {
        // A subdomain containing a dash before the apex
        let s = "https://sub-mid.lehuwadi-zakatari.mns.alt";
        let name: Name = s.parse().expect("parse with subdomain containing dash");
        assert_eq!(name.to_string(), "lehuwadi-zakatari");
    }

    #[test]
    fn test_from_str_rejects_malformed_hyphen() {
        // Hyphen at wrong position
        assert!("davufezo-hosojise".parse::<Name>().is_ok()); // correct
        assert!("davuf-ezohosojise".parse::<Name>().is_err()); // wrong hyphen pos
    }
}

#[cfg(test)]
mod proptests {
    use super::*;
    use proptest::prelude::*;

    proptest! {
        #[test]
        fn prop_string_roundtrip(ordinal in 0u64..1_099_511_627_775u64) {
            let name = Name::from_ordinal(ordinal).unwrap();
            let encoded = name.to_string();
            let decoded: Name = encoded.parse().unwrap();
            prop_assert_eq!(name, decoded);
        }

        #[test]
        fn prop_ordinal_roundtrip(ordinal in 0u64..1_099_511_627_775u64) {
            let name = Name::from_ordinal(ordinal).unwrap();
            prop_assert_eq!(ordinal, name.to_ordinal());
        }
    }
}
