#!/usr/bin/env python3
"""Export the curated final lists into the mns crate as Rust consts.

Reads scripts/data/final/prefixes.txt + suffixes.txt (the pipeline source of
truth) and writes mns/src/pools.rs with PREFIXES and SUFFIXES const arrays,
so name.rs (and the rest of the crate) can consume the pools directly.

Usage: export.py [--check]   (--check: only verify the crate file matches)
"""
import argparse
import sys
from pathlib import Path

import generate

SRC_PRE = generate.FILTERED_DIR.parent / "final" / "prefixes.txt"
SRC_SUF = generate.FILTERED_DIR.parent / "final" / "suffixes.txt"
OUT = Path("mns") / "src" / "pools.rs"

HEADER = """// @generated by scripts/curate/export.py — do not edit by hand.
// Source of truth: scripts/data/final/prefixes.txt + suffixes.txt
// (rebuild with `just curate`).
//
// Curated 4-letter CVCV piece pools (4096 each). Every piece is
// consonant-vowel-consonant-vowel over consonants `b d f g h j k l m n p r s
// t v w z` and vowels `a e i o u`: open-syllable, profanity- and rule-checked.
// See design/names.md for the reasons and design docs.
"""

TEST_FOOTER = r'''

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::*;

    #[test]
    fn lists_are_4096_and_unique() {
        for (name, list) in [("prefixes", PREFIXES), ("suffixes", SUFFIXES)] {
            assert_eq!(list.len(), 4096, "{name} length");
            let set: HashSet<&str> = list.iter().copied().collect();
            assert_eq!(set.len(), 4096, "{name} has duplicates");
        }
    }

    #[test]
    fn tokens_are_cvcv_over_curated_alphabet() {
        let cons: HashSet<char> = "bdfghjklmnprstvwz".chars().collect();
        let vow: HashSet<char> = "aeiou".chars().collect();
        for t in PREFIXES.iter().chain(SUFFIXES.iter()) {
            let b = t.as_bytes();
            assert_eq!(b.len(), 4, "bad length: {t}");
            assert!(
                cons.contains(&(b[0] as char))
                    && vow.contains(&(b[1] as char))
                    && cons.contains(&(b[2] as char))
                    && vow.contains(&(b[3] as char)),
                "not CVCV over the curated alphabet: {t}"
            );
        }
    }

    #[test]
    fn no_banned_substrings_or_reduplication() {
        for t in PREFIXES.iter().chain(SUFFIXES.iter()) {
            assert!(!t.contains("uw"), "contains 'uw': {t}");
            let b = t.as_bytes();
            assert!(
                !(b[0] == b[2] && b[1] == b[3]),
                "reduplicated syllable: {t}"
            );
            for bad in ['c', 'q', 'x', 'y'] {
                assert!(!t.contains(bad), "forbidden letter {bad} in {t}");
            }
        }
    }
}
'''


def load(path):
    toks = [l.strip() for l in open(path) if l.strip()]
    assert len(toks) == 4096 and len(set(toks)) == 4096, path
    return toks


def fmt(toks, name):
    lines = [f"pub const {name}: [&str; {len(toks)}] = ["]
    for i in range(0, len(toks), 12):
        chunk = ", ".join(f'"{t}"' for t in toks[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("];")
    return "\n".join(lines)


def render(pre, suf):
    return (HEADER
            + "\n" + fmt(pre, "PREFIXES") + "\n\n" + fmt(suf, "SUFFIXES")
            + TEST_FOOTER)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    pre, suf = load(SRC_PRE), load(SRC_SUF)
    body = render(pre, suf)

    if args.check:
        if not OUT.exists() or OUT.read_text() != body:
            print("FAIL: mns/src/pools.rs is out of date", file=sys.stderr)
            return 1
        print("OK: mns/src/pools.rs matches scripts/data/final")
        return 0

    OUT.write_text(body)
    print(f"wrote {OUT}  (prefixes {len(pre)}, suffixes {len(suf)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())